### ISSUE TITLE
Define facilitator manifest and manifest schema

### ISSUE THREAD

**Issue by deepesh-kn** [mosaicdao/facilitator#287]
- Implement a function to validator the manifest file
- Proposed facilitator manifest:
    ```yaml=
    version: "v0.14"
    architecture_layout: M1
    personas:        
        facilitator
        validator        
    chain: // section for m0 utility chains
    metachain: // section metachains for m1
        auxiliary:
            avatar_account: ""
            node_endpoint: ""
            graph_ws_endpoint: ""
            graph_rpc_endpoint: ""
        origin:
            avatar_account: ""
            node_endpoint: ""
            graph_ws_endpoint: ""
            graph_rpc_endpoint: ""
    accounts:
        "0xac7E36b3cdDb14Bf1c67dC21fFB24C73d03d8FF7":
            keystore_path: ""
            keystore_password_path: ""
    origin_contract_addresses:
        erc20_gateway: ""
    facilitate_tokens:
        - 0xA
        - 0xB
    ```
